### ISSUE TITLE
Dialog closes unexpectedly when scrolling to bottom of accordion 

### ISSUE THREAD

**Issue by oetlinge** [IBM/carbon-components-angular#1577] opened 2020-10-23 22:13 UTC
## Detailed description

> Describe in detail the issue you're having.

When accordion items are present in a dialog and the contents require a scrollbar to handle vertical overflow, scrolling to the bottom of the accordion and clicking/focusing on the elements near the bottom cause the dialog to close unexpectedly. It seems as though the dialog is detecting that the y coordinate of the active element lies beyond the bottom of the screen. Zooming in/out on the page affects the threshold beyond which focused elements cause the dialog to close.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Accordion/Accordion Item 

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected the dialog to remain open instead of closing.

> What browser are you working in?

Chrome. Observed this behaviour for Chromium browsers (e.g. Chrome, Opera), but confirmed it is not an issue in Firefox.

> What version of the Carbon Design System are you using?

4.19.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Sterling UIHub. Prefer to have this resolved before end of 4Q 2020.

## Steps to reproduce the issue

https://github.com/cal-smith/dialogapp

1. Click on the button to open the dialog.
2. Expand one of the accordions on the dialog.
3. Tab through the elements within the accordion. Somewhere near the bottom of the accordion, one of the elements will trigger the dialog to close as soon as it receives focus.

## Additional information

* When accordion elements were replaced with divs, the issue was no longer reproducible, even on Chromium browsers.

**Comment by cal-smith** [comment] 2020-11-05 21:36
So a bit of googeling and tinkering later and it appears that we need to add `position: relative;` (or really, anything other than `static`) to the `.scrollable-content`, so this looks like a fix you can apply in your styles!

Thanks to https://stackoverflow.com/questions/22898335/strange-behavior-of-overflow-auto-on-chrome for pointing me in the right direction.

Let me know if this fixes things for you @oetlinge and we can close this issue!

**Comment by cal-smith** [comment] 2020-11-05 22:48
Confirmed fixed!

**Closed by cal-smith** 2020-11-05 22:48 UTC
Labels: component: Dialog
