### ISSUE TITLE
Toolbar search in table not working

### ISSUE THREAD

**Issue by carmelajanegarcia** [IBM/carbon-components-angular#1856] opened 2021-06-22 15:55 UTC
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?
_Bug_

> Is this issue related to a specific component?
_Table, Search_

> What did you expect to happen? What happened instead? What would you like to see changed?
_For search in table to work as expected like in the previous versions_

> What browser are you working in?
_Google chrome Version 91.0.4472.114_

> What version of the Carbon Design System are you using?
`"carbon-components": "^10.37.0",`
` "carbon-components-angular": "^4.52.1",`
`"@carbon/colors": "^10.8.0",`
   ` "@carbon/grid": "^10.9.1",`
   ` "@carbon/icons-angular": "^11.2.2",`
    `"@carbon/import-once": "^10.3.0",`
`    "@carbon/layout": "^10.8.1",`
   ` "@carbon/motion": "^10.6.0",`

## Steps to reproduce the issue

Happens in the documentation page of carbon angular
https://angular.carbondesignsystem.com/?path=/story/components-table--with-toolbar

## Additional information

<img width="1422" alt="Screenshot 2021-06-22 at 11 43 26 PM" src="https://user-images.githubusercontent.com/52859232/122957299-5f37d280-d3b4-11eb-8f65-db61a124a2a1.png">

**Comment by grenobnik** [comment] 2021-06-28 12:49
This is quite annoying that I cannot update my carbon-components packages due to this bug in `<ibm-table-toolbar-search>`.  It is not just visual, the search field does not expand any more. Last known working version in my setup is 
```
"carbon-components": "10.31.0",
"carbon-components-angular": "4.48.3",
```
![image](https://user-images.githubusercontent.com/6929951/123638699-bfe56600-d81f-11eb-954d-7dc25a9aa909.png)

**Comment by Gabuardi** [comment] 2021-07-05 18:41
Working on it!

**Comment by Licen-it** [comment] 2021-07-16 18:54
@Gabuardi sorry i noticed you were working on it after creating the PR

**Comment by Gabuardi** [comment] 2021-07-16 21:37
@Licen-it no problem... I over complicate my solution, yours looks more cleaner so would say its better

however I noticed several things for the future of carbon versions, for example there is no need on wrap the whole component in another div for the `.bx--search` I think would be better use the `@hostBinding`. 
Another thing is the fact of have the `search-component` and `search-toolbar-component` is confusing, if there is a reason to have different components definitely is not being reflected right now since the only difference is the the `toolbar-search-component` set the input `expandable` to true.

and the last thing I can remember is the sizes... for one strange reason the `search-component` has in the options size the *md* size which doesn't exist and what is worse is this size is being set as the default for the component breaking the styles

lastly, you confirmed this component actually make a search? at least on the storybook code the toolbar search seems not be working when you type something

**Comment by Gabuardi** [comment] 2021-07-16 21:38
@zvonimirfras I think would be better assign it to @Licen-it since she/he resolve the issue - please also keep in mind my previous observation

**Comment by Licen-it** [comment] 2021-07-16 21:44
yes i noticed the same, the only reason i didn't remove that div and moved everything to `@hostBinding` is that i'm not sure it's legal to assign the `role="search"` to a non standard element and also because i wanted to fix the issue without having to change too much the component...just in case some choices were done on purpose in storybook the search is not hooked to the table...you have to manually hook it

**Closed** 2021-07-26 13:49 UTC
