### ISSUE TITLE
Carbon changed scss and Tabs has now issues

### ISSUE THREAD

**Issue by Licen-it** [IBM/carbon-components-angular#1543] opened 2020-09-29 11:31 UTC
## Detailed description

> Describe in detail the issue you're having.

I noticed a small icon (tabs trigger) appearing before my tabs after updating to latest version. Investigating what changed, it seems all related to this commit: https://github.com/carbon-design-system/carbon/commit/cdc96da636a3f8c622283c04a13f1b2acb0b39c1
It seems carbon-components changed the strategy on how to show/use the trigger and now 2 issues appeared in the angular version of Tabs:
1. The trigger is always visible
2. On small displays the tabs are still visible the same way it happens on a normal screen, instead of compressing down under the trigger button

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

TabHeaders, TabHeaderGroup

> What version of the Carbon Design System are you using?

latest of both carbon-components and carbon-components-angular

## Additional information

![image](https://user-images.githubusercontent.com/35496522/94552933-a216b080-024f-11eb-85e4-b01a23fff4bb.png)

**Comment by cal-smith** [comment] 2020-09-29 15:26
Hey 👋 We're currently waiting on a better upstream fix. You can follow https://github.com/carbon-design-system/carbon/pull/6928 and https://github.com/carbon-design-system/carbon/pull/6803 for now though 👍

**Comment by cal-smith** [comment] 2020-09-29 20:26
Closing as a dupe of #1497

**Closed by cal-smith** 2020-09-29 20:26 UTC
Labels: style
