### ISSUE TITLE
Combobox styling in Safari browser

### ISSUE THREAD

**Issue by temacode** [IBM/carbon-components-angular#1565] opened 2020-10-09 12:44 UTC
Detailed description

> Describe in detail the issue you're having.

Combobox styling in Safari is wrong. Maybe -webkit-appearance: none; missing.  

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Combobox

> What browser are you working in?

Safari 14.0

> What version of the Carbon Design System are you using?

"@carbon/elements": "^10.18.0",
"@carbon/icons-angular": "^11.0.1",
"@carbon/motion": "^10.7.0",
"@carbon/themes": "^10.11.2",
"carbon-components": "^10.19.0",
"carbon-components-angular": "^4.15.1",

## Additional information
<img width="497" alt="Снимок экрана 2020-10-09 в 15 36 26" src="https://user-images.githubusercontent.com/52513630/95584362-4534aa80-0a46-11eb-9961-ee6b58c66f64.png">

<img width="494" alt="Снимок экрана 2020-10-09 в 15 36 37" src="https://user-images.githubusercontent.com/52513630/95584368-4960c800-0a46-11eb-9bc2-be48da51121d.png">

<img width="561" alt="Снимок экрана 2020-10-09 в 15 40 30" src="https://user-images.githubusercontent.com/52513630/95584375-4bc32200-0a46-11eb-9817-a3e883596180.png">

**Comment by cal-smith** [comment] 2020-10-09 16:19
I can't reproduce the issue in the storybook ... Ensure that you're using the latest version of `carbon-components`, and that your `autoprefixer` is configured correctly (Carbon doesn't manually add any vendor specific prefixes).

**Comment by cal-smith** [comment] 2020-11-04 18:23
Since you haven't responded at all in roughly a month, and I can't reproduce this, I'm going to close this.

**Closed by cal-smith** 2020-11-04 18:23 UTC
Labels: can't reproduce, style
