### ISSUE TITLE
Accessibility issue in content switcher component

### ISSUE THREAD

**Issue by bikashpattnayak** [IBM/carbon-components-angular#1974] opened 2022-01-21 16:42 UTC
## Accessibility issue in content switcher component

For **ibm-content-switcher,** the accessibility checker gives  the error 
"The ARIA attribute 'aria-selected' is not valid for the element <button> with ARIA role 'button'"

![image](https://user-images.githubusercontent.com/19235808/150565500-28e2c809-ff45-4da3-80cb-71c803a0f8b6.png)

![image](https://user-images.githubusercontent.com/19235808/150565602-f9f6fe5e-63dd-47e0-91c0-3642da3c6767.png)

**Comment by maicongodinho** [comment] 2022-07-01 13:04
Hi @bikashpattnayak could you tell us what version of carbon-components-angular you are using?

**Comment by bikashpattnayak** [comment] 2022-07-01 13:17
hi @maicongodinho, I am currently using "carbon-components-angular": "^4.40.0" in my project.

**Comment by bikashpattnayak** [comment] 2022-07-01 19:02
Hi @maicongodinho , I did the upgrade to the exact version 4.59.7. Still see the same issue.

![image](https://user-images.githubusercontent.com/19235808/176955006-eb10df7c-3285-460f-96c9-5a1ce9d22aa1.png)

**Comment by maicongodinho** [comment] 2022-07-03 02:32
Can you share the template with us? (how you are using the ibm-content-switcher)

**Comment by maicongodinho** [comment] 2022-07-03 02:58
Strange @bikashpattnayak, I created a component with just that component and ran the IBM Accessibility Checker tool. No errors were found as reported.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/94566751/177022668-4f62d4b2-a59b-4062-b9b8-5140f6a84ae0.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/94566751/177022682-59c3b7ef-c289-4d34-8b19-9afc01ae57e6.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/94566751/177022691-ffb0af96-7336-4e93-a446-c3924faf83ea.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/94566751/177022718-aa234304-f697-474d-ae76-a936d6941be8.png">

**Comment by maicongodinho** [comment] 2022-07-03 02:59
You are sure that error is from this component?

**Comment by Akshat55** [comment] 2022-08-26 04:25
@bikashpattnayak Can you verify if your accessibility assessment plugin is up to date? I cannot reproduce this error as well via storybook or creating a demo app.

**Comment by Akshat55** [comment] 2022-09-20 04:25
The role attribute of the button that the `ibmContentOption` directive is assigned to is set to `button` instead of `tab`. `ibmContentOption` directive automatically assigns the role `tab`, so by removing the role on your part (Assuming you have overriden it) will resolve this issue.

**Closed by Akshat55** 2022-09-20 04:25 UTC
