### ISSUE TITLE
<ibm-content-switcher state is not correct when there are two or more <ibm-content-switcher

### ISSUE THREAD

**Issue by klower** [IBM/carbon-components-angular#705] opened 2019-08-16 05:39 UTC
![image](https://user-images.githubusercontent.com/4176873/63145745-28ac0680-c02b-11e9-9542-19bbb14b83a3.png)
I have two <ibm-content-switcher in my page, when I click the first switcher, the another switcher state is not correct

**Comment by cal-smith** [comment] 2019-08-16 13:13
Could you provide a repro codesandbox/stackblitz, or otherwise some code to reproduce. Testing locally, it seems like I can have as many content switchers, with seperate values, as I like.

**Comment by klower** [comment] 2019-08-19 01:25
![image](https://user-images.githubusercontent.com/4176873/63233509-22a06a80-c263-11e9-9176-2592c71fcf11.png)
all tabindex of the button is -1

**Comment by cal-smith** [comment] 2019-08-19 16:32
Right, I still can't reproduce this locally.

the following code in the storybook works as expected:

```html
<ibm-content-switcher (selected)="selected($event)">
	<button ibmContentOption name="First">First section</button>
	<button ibmContentOption name="Second">Second section</button>
	<button ibmContentOption name="Third">Third section</button>
</ibm-content-switcher>

<ibm-content-switcher (selected)="selected($event)">
	<button ibmContentOption name="Second">Second section</button>
	<button ibmContentOption name="Third">Third section</button>
</ibm-content-switcher>
```

A full code sample, codesandbox, or stackblitz would help debug this situation.

(This link will give you a stackblitz to start from https://stackblitz.com/fork/carbon-angular-base)

**Comment by klower** [comment] 2019-08-21 02:35
![image](https://user-images.githubusercontent.com/4176873/63398157-3ed90e80-c3ff-11e9-8eb8-f4652bb9da6b.png)
when I select one of the content switch, another is not selected

**Comment by cal-smith** [comment] 2019-08-21 21:20
Could you share the link here? It's still not clear to me how this is happening.

**Comment by klower** [comment] 2019-08-22 01:18
@cal-smith https://stackblitz.com/edit/carbon-angular-base-vvtwfe?file=src%2Fapp%2Fapp.component.html

**Comment by klower** [comment] 2019-08-22 01:18
just add these codes below:
 <ibm-content-switcher>
      <button ibmContentOption name="Value1">Value1</button>
         <button ibmContentOption name="Volume1">Volume1</button>
 </ibm-content-switcher>

  <ibm-content-switcher>
            <button ibmContentOption name="Value2">Value2</button>
            <button ibmContentOption name="Volume2">Volume2</button>
  </ibm-content-switcher>

**Comment by klower** [comment] 2019-08-22 01:19
just add these codes below:
` <ibm-content-switcher>
      <button ibmContentOption name="Value1">Value1</button>
         <button ibmContentOption name="Volume1">Volume1</button>
 </ibm-content-switcher>

  <ibm-content-switcher>
            <button ibmContentOption name="Value2">Value2</button>
            <button ibmContentOption name="Volume2">Volume2</button>
  </ibm-content-switcher>`

**Comment by klower** [comment] 2019-08-23 01:32
@cal-smith is it a bug?

**Comment by zvonimirfras** [comment] 2021-01-18 21:35
Can't reproduce and long time passed since the last update to the issue, so closing. Feel free to reopen with reproduction step if still relevant.

**Closed by zvonimirfras** 2021-01-18 21:35 UTC
Labels: component: ContentSwitcher
