### ISSUE TITLE
Modal contents scroll overflow indicator appearing above modal buttons

### ISSUE THREAD

**Issue by aishwaryamyana** [IBM/carbon-components-angular#1572] opened 2020-10-21 09:05 UTC
Carbon Modal component Style getting disturbed in IE11 browser .

Attaching the screenshot to refer.

![carbon-modal-IE11](https://user-images.githubusercontent.com/53562295/96698307-962f9180-13aa-11eb-899f-6cfe25599196.png)

**Comment by cal-smith** [comment] 2020-10-21 17:43
Can you recreate that behaviour in the storybook (https://angular.carbondesignsystem.com/)? Also, can you share the template you're using for that modal?

**Comment by aishwaryamyana** [comment] 2020-10-22 07:15
Not able to open storybook in IE11. It seems storybook does not have IE support.  But this is reproducible for all the modals across application in IE11.

template - <ibm-placeholder></ibm-placeholder>

**Comment by cal-smith** [comment] 2020-10-27 20:44
Can you reproduce the issue in an isolated app (`ng new test-app` or similar)? I have a feeling it's a styling issue, but it's hard to know if it's something that's isolated to your app, or if it's something on the `carbon-components` side. I haven't ruled out our layout causing the issue, but that seems unlikely to me.

Also `<ibm-placeholder></ibm-placeholder>` isn't your modal template. Can you share the template you are using for your modal component?

**Comment by BryanWooCH** [comment] 2021-02-01 00:05
Hi @cal-smith 

I have same issue with this one. It is not only on IE11 but also the chrome as well.

I also can reproduce this bug on the official story book.
1. On data passing example.
2. Keep open the modal and close.
3. It will show as below at some point. 




![image](https://user-images.githubusercontent.com/55734917/106402323-11f6ab00-647d-11eb-9db4-bf38a9e5e8a0.png)

**Comment by cal-smith** [comment] 2021-02-01 22:33
I can't reproduce it on chrome.

If this is an issue that happens _at random_ I'm not sure how we're expected to fix it.

Since no one has been able to provide a _minimal reproduction environment_ in the 3 months this has been open, and it appears to be an artifact of some very specific browser conditions I'm going to close this issue.

Feel free to re-open with a minimal reproduction.

**Closed by cal-smith** 2021-02-01 22:33 UTC
Labels: IE11, component: Modal, style
