### ISSUE TITLE
Typescript Error for toggle component

### ISSUE THREAD

**Issue by huineng** [IBM/carbon-components-angular#1401] opened 2020-07-10 21:02 UTC
Angular Version: 10.0.2
Typescript: 3.9.6
carbon-components: "^10.15.0",
carbon-components-angular: "^4.10.1",

generates 1 warning

```
[at-loader] ./node_modules/carbon-components-angular/toggle/toggle.component.d.ts:95:5 
    TS2416: Property 'change' in type 'Toggle' is not assignable to the same property in base type 'Checkbox'.
  Type 'EventEmitter<ToggleChange>' is not assignable to type 'EventEmitter<CheckboxChange>'.
    Types of property 'observers' are incompatible.
      Type 'Observer<ToggleChange>[]' is not assignable to type 'Observer<CheckboxChange>[]'.
        Type 'Observer<ToggleChange>' is not assignable to type 'Observer<CheckboxChange>'.
          Type 'CheckboxChange' is not assignable to type 'ToggleChange'. 
```

**Comment by Aracturat** [comment] 2020-07-13 14:22
Duplicate of https://github.com/IBM/carbon-components-angular/issues/1343

**Comment by Donisius** [comment] 2020-07-13 16:47
Does this warning show up with angular 9?

**Comment by cal-smith** [comment] 2020-07-29 20:11
Closing in favor of #1343

**Closed by cal-smith** 2020-07-29 20:11 UTC
