### ISSUE TITLE
ibm-table-toolbar-search clear button not working in Firefox

### ISSUE THREAD

**Issue by nikhides** [IBM/carbon-components-angular#434] opened 2019-03-11 10:35 UTC
## Detailed description

Toolbar search close button not clearing the text present into search text box in Mozilla. 

## Steps to reproduce the issue

1. Include toolbar search in page
2. Open that page in Firefox.
3. Write something in search text box 
4. try to clear by pressing clear button
5. You will observe that text does not get cleared.

## Additional information
I have attached screenshot of same
![image (4)](https://user-images.githubusercontent.com/48436994/54117741-79ce2380-4417-11e9-89d8-bfe020ab3a16.png)

**Comment by cal-smith** [comment] 2019-03-11 15:08
Seems to work for me ... a couple of questions:

1. what version of firefox?
2. are you using the experimental styles?
3. what version of carbon-components and carbon-components-angular?
4. can you create a minimal reproduction? (on [codesandbox](https://codesandbox.io/s/0129r494ql) ideally)

**Comment by nikhides** [comment] 2019-03-12 04:37
> Seems to work for me ... a couple of questions:
> 
> 1. what version of firefox?
> 2. are you using the experimental styles?
> 3. what version of carbon-components and carbon-components-angular?
> 4. can you create a minimal reproduction? (on [codesandbox](https://codesandbox.io/s/0129r494ql) ideally)

what version of firefox?
  Please find attached image for Firefox version
are you using the experimental styles?
Yes
what version of carbon-components and carbon-components-angular?
carbon-components version :- ^9.76.0
carbon-components-angular version :- ^2.32.1
can you create a minimal reproduction? (on codesandbox ideally)
https://codesandbox.io/s/ol521qn4my
<img width="657" alt="Screen Shot 2019-03-12 at 10 05 31 AM" src="https://user-images.githubusercontent.com/48436994/54174871-a5e8b380-44ae-11e9-8410-009dbd2e9232.png">

**Comment by cal-smith** [comment] 2019-03-12 17:28
Ah, I see the issue now ... the close button needs `z-index: 1` in firefox to bring it to the front

**Comment by cal-smith** [comment] 2019-03-18 17:52
Seems to be fixed as of carbon-components `9.84.14`

**Closed by cal-smith** 2019-03-18 17:52 UTC
Labels: bug, component: Table, style
