### ISSUE TITLE
Button margins are only applied for secondary then primary combination

### ISSUE THREAD

**Issue by hvlawren** [IBM/carbon-components-angular#170] opened 2018-10-15 19:02 UTC
<img width="480" alt="screen shot 2018-10-15 at 2 52 20 pm" src="https://user-images.githubusercontent.com/36514864/46971495-19b29b80-d08a-11e8-9b7d-51a38b09e04c.png">
<img width="480" alt="screen shot 2018-10-15 at 2 53 13 pm" src="https://user-images.githubusercontent.com/36514864/46971496-1a4b3200-d08a-11e8-9cbc-353fbd130c1c.png">
<img width="481" alt="screen shot 2018-10-15 at 2 54 51 pm" src="https://user-images.githubusercontent.com/36514864/46971553-4c5c9400-d08a-11e8-8478-7c96452e4e0e.png">

## Detailed description

> Describe in detail the issue you're having.

A margin is applied only for some button combinations

> Is this a feature request (new component, new icon), a bug, or a general issue?

I found this when working with modals, but believe it would happen with any area with multiple buttons.

> Is this issue related to a specific component?

Buttons

> What did you expect to happen? What happened instead? What would you like to see changed?

Consistent margins when multiple buttons are used

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

**Comment by hvlawren** [comment] 2018-10-15 19:02
For now I'll just use secondary & primary, though that's not optimal.

**Comment by stanislavgeorgiev** [comment] 2018-10-16 01:49
You could also do:
```
.bx--btn+.bx--btn {
    margin-left: $spacing-md;
}
```

There was an opened issue with the Carbon Components repo but it got closed: https://github.com/IBM/carbon-components/issues/1085

**Comment by zvonimirfras** [comment] 2018-10-16 12:39
As Stan mentioned, this is working as intended, workaround is the snippet he posted, closing for now.

**Closed by zvonimirfras** 2018-10-16 12:39 UTC
