### ISSUE TITLE
Expandable row expanding past table when more than two columns

### ISSUE THREAD

**Issue by jpacock** [IBM/carbon-components-angular#272] opened 2018-11-14 16:05 UTC
Hi,

I am currently on a client project implementing a design for a client.

I am seeing an issue with table expansion where if I have more than 2 columns (as the table expansion story shows), then when the row is expanded, the additional columns will extend past the the table. 

Here shows the row expanded with 2 columns:
<img width="831" alt="screen shot 2018-11-14 at 9 57 07 am" src="https://user-images.githubusercontent.com/8479854/48494843-49bd9d80-e7f4-11e8-8cc8-de33f3d93898.png">

Then when I add the third column without expanding:
<img width="811" alt="screen shot 2018-11-14 at 10 04 02 am" src="https://user-images.githubusercontent.com/8479854/48495041-c51f4f00-e7f4-11e8-8ba1-5b34933535a6.png">

There here is the third column when I expand:
<img width="869" alt="screen shot 2018-11-14 at 9 57 55 am" src="https://user-images.githubusercontent.com/8479854/48494817-3d394500-e7f4-11e8-9a52-5af015e22e6f.png">

Then here I added a fourth column expanded:
<img width="926" alt="screen shot 2018-11-14 at 10 02 32 am" src="https://user-images.githubusercontent.com/8479854/48495086-dcf6d300-e7f4-11e8-8bb2-3807733727f0.png">

**Comment by esuau** [comment] 2018-12-06 09:17
This issue might have been resolved by #292.

**Comment by cal-smith** [comment] 2018-12-19 02:37
Looks related for sure ... @jpacock are you still seeing this post `v2.3.1`?

**Comment by ninja511** [comment] 2020-06-29 17:00
closing pending additional information: can't reproduce

**Closed by ninja511** 2020-06-29 17:00 UTC
Labels: can't reproduce, component: Table
