### ISSUE TITLE
Definition tooltip - Not completely visible

### ISSUE THREAD

**Issue by Swati-Jaiswal** [IBM/carbon-components-angular#1122] opened 2020-03-13 14:33 UTC
I am using definition-tooltip with placement = top inside a table

Issue:
I have added definition-tooltip to a table header, but on hover the tooltip it is not fully visible at the top.

<img width="716" alt="definition tooltip issue" src="https://user-images.githubusercontent.com/46749098/76629804-e452fb80-6564-11ea-9dde-660d64619626.png">

Expected behaviour:
The definition-tooltip should be fully visible.

**Comment by Donisius** [comment] 2020-03-23 19:08
Using the table model and a custom table header, the tooltip seems to be visible. Can you provide a minimal reproduction of your issue and how you are creating your table so we can look further into it?
<img width="726" alt="Screen Shot 2020-03-23 at 3 05 46 PM" src="https://user-images.githubusercontent.com/45505172/77353749-ec0a6100-6d17-11ea-9366-cd43255951c5.png">

**Comment by Swati-Jaiswal** [comment] 2020-03-30 13:01
Hi @Donisius,
I am not adding table title and I don't have any padding around my table. For this scenario the tooltip is not getting displayed.

<img width="552" alt="Screenshot 2020-03-30 at 6 30 28 PM" src="https://user-images.githubusercontent.com/46749098/77915154-96542c80-72b4-11ea-9cd0-868d626d8a93.png">

**Comment by Donisius** [comment] 2020-03-31 18:16
Seems to also be a problem in the styling since I was able to reproduce the issue in react as well. The issue can be tracked at https://github.com/carbon-design-system/carbon/issues/5759

**Comment by Donisius** [comment] 2020-04-03 16:09
Hello @Swati-Jaiswal, removing the `overflow-x: auto` from `.bx--data-table-container` seems to "fix" it. Be warned that it _may_ cause issues since I have not tested its' effects. You can also remove the table container. After discussion with Josh from the carbon-design-system repo: https://github.com/carbon-design-system/carbon/issues/5759, it seems to be a limitation within CSS and there's not much that they can do about it.

**Comment by cal-smith** [comment] 2020-04-23 18:37
Going to close this since it seems like there's a possible solution, and we're limited by the carbon-components CSS

**Closed by cal-smith** 2020-04-23 18:37 UTC
