### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by superchenwei** [IBM/carbon-components-angular#877] opened 2019-10-30 02:49 UTC
ERROR in ./node_modules/carbon-components-angular/checkbox/checkbox.component.ngfactory.js
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\carbon-components-angular\checkbox\checkbox.component.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please 
open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/carbon-components-angular/toggle/toggle.component.ngfactory.js
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\carbon-components-angular\toggle\toggle.component.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please 
open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (C:\Users\WEICHEN\bigdata\edpa-ui-admin\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by superchenwei** [comment] 2019-10-30 02:54
it's work fine when run command "npm run build" with  "carbon-components-angular": "^3.11.3",
after I upgrade carbon-components-angular in version 3.16.0 got error above.
check it please

**Comment by cal-smith** [comment] 2019-10-30 21:39
What version of Angular is this with? What happens when you update to our latest release (3.22.0)?

**Comment by jesatrix** [comment] 2019-11-01 19:17
@cal-smith I am also experiencing the same error. 

_Package versions:_
carbon-components-angular: `3.23.1`
angular: `8.2.9`
typescript: `3.5.3`
npm: `6.12.1`
node: `10.17.0`

_Error:_
![Screen Shot 2019-11-01 at 2 03 35 PM](https://user-images.githubusercontent.com/5224165/68049769-ad650300-fcb1-11e9-9551-b9ba4e1fc5a2.png)

**Comment by jesatrix** [comment] 2019-11-01 19:45
Additionally, this was not happening for us on carbon-components-angular: `3.15.2`, which is the version we have live in master. The rest of the above included versions are the same.

**Comment by cal-smith** [comment] 2019-11-04 17:18
@superchenwei @jesatrix do either of you have a minimal reproduction you can share? Just a simple Angular CLI app that exhibits the problem would be amazing.

**Comment by Pablodotnet** [comment] 2019-11-05 21:27
ng build --prod present errors using angular version 7.2.6 too.

**Comment by Pablodotnet** [comment] 2019-11-05 21:41
The issue comes since version 3.21.0 of carbon angular components

**Comment by cal-smith** [comment] 2019-11-08 22:05
Hey all! After some investigation it seems like deep imports to modules are part of the issue (i.e. import { FooModule } from 'carbon-components-angular/foo/foo.module';). Deep imports for types are fine. It’s still not super clear to me why this is happening, but it should be possible to get your apps building with 3.24.0 or higher by removing deep module imports

**Comment by cal-smith** [comment] 2019-11-13 17:02
This should be resolved with `@carbon/icons-angular@10.7.0` and `carbon-components-angular@3.25.0`

**Closed by cal-smith** 2019-11-13 17:02 UTC
Labels: bug
