### ISSUE TITLE
side-nav-item component inside ui-shell is not accessibility compliance.

### ISSUE THREAD

**Issue by shroffsmiti** [IBM/carbon-components-angular#1162] opened 2020-03-30 17:38 UTC
ibm-sidenav-item does not set the roles correctly for menu-item. 
Here https://github.com/IBM/carbon-components-angular/blob/7f9ebb78a41ea29344b80e0343e3d3bfab89f36d/src/ui-shell/sidenav/sidenav-item.component.ts#L22

It violates accessibility rule:
>  The WAI-ARIA role(s) and/or attribute(s) must be valid for the relevant element.

**Comment by Donisius** [comment] 2020-04-01 20:40
Hello @shroffsmiti!, I am using all the rulesets available in the latest DAP rule archive but I cant seem to come across this violation, which rule sets are you using?

**Comment by shroffsmiti** [comment] 2020-04-02 21:35
this is the rule
> HAAC_Aria_Native_Host_Sematics
which u can find here https://aat.w3ibm.mybluemix.net/tools/auth/rules.html?accountId=f154a93a-a580-4a2d-ac62-62262fe6d9f5
@Donisius

**Comment by ninja511** [comment] 2020-06-29 16:59
closing pending additional information: can't reproduce

**Closed by ninja511** 2020-06-29 16:59 UTC
Labels: accessibility, bug, can't reproduce, component: UI Shell
