### ISSUE TITLE
ERROR TypeError: Cannot read property ‘isUpdate’ of null on multi-select dropdown

### ISSUE THREAD

**Issue by n16** [IBM/carbon-components-angular#783] opened 2019-09-27 17:07 UTC
## Detailed description

> Describe in detail the issue you're having.
1. open a multi-select and select any item
2. while the drop-down is open, unselect the same item
Then Cannot read property ‘isUpdate’ of null appears

> Is this a feature request (new component, new icon), a bug, or a general issue?
No

> Is this issue related to a specific component?
multi-select dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome/Safari/Firefox

> What version of the Carbon Design System are you using?
“carbon-components-angular”: “^3.12.6"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. open a multi-select and select any item
2. while the drop-down is open, unselect the same item
Then Cannot read property ‘isUpdate’ of null appears

## Additional information
I saw a bug closed on same issue, but I did not have an option to reopen, so I had to create a new bug. This is the link to that issue:
https://github.com/IBM/carbon-components-angular/issues/686

* Screenshots or code
* Notes

**Comment by n16** [comment] 2019-09-27 17:08
![Screen Shot 2019-09-27 at 10 03 35 AM](https://user-images.githubusercontent.com/4207929/65787860-bf7ddf80-e10e-11e9-851a-af4ccc8956b6.png)

**Comment by cal-smith** [comment] 2019-10-21 18:58
Just want to confirm you're still seeing this issue with the latest `carbon-components-angular`? If you are, can you provide a minimal repro environment/code sample/codesandbox/stackblitz? I can't recreate this in the storybook

**Comment by n16** [comment] 2019-10-21 19:03
What is the latest version of carbon-components-angular?

**Comment by cal-smith** [comment] 2019-10-22 21:05
You do a `npm info carbon-components-angular` to check ... right now it's `3.21.0`

**Comment by n16** [comment] 2019-10-22 21:11
Yes, this is what I have. Then, the issue still is visible in this version. 
To reproduce it:
Have a table with the multi-select filters populated and then do the steps I provided above. You'll hit the issue.

**Comment by cal-smith** [comment] 2020-01-09 19:23
Just checking again that you're still experiencing this issue with the latest version? If so could you _please_ provide a minimal reproduction environment (basic cli app, code snippet, anything) since I can't reproduce this error locally.

**Comment by n16** [comment] 2020-01-09 19:30
Yes, with the latest version also this issue is seen. I implemented a work-around into our solution so it can bypass the error. However, this is not an optimal fix since other users would face the issue. 

The reproducing steps are still the same as mentioned above.

**Comment by cal-smith** [comment] 2020-01-10 15:58
Sorry if I haven't been clear - I cannot reproduce the issue using only the steps you have given me. I need an isolated environment that exhibits the issue to efficiently fix it. Alternatively, if you have an idea of what the cause is **please** submit a PR with a proposed fix and we can take it from there.

**Comment by ninja511** [comment] 2020-06-29 17:01
closing pending additional information: can't reproduce

**Closed by ninja511** 2020-06-29 17:01 UTC
Labels: bug, can't reproduce, component: Dropdown

**Comment by pablo-sg-pacheco** [comment] 2023-06-01 02:54
Same problem here
