### ISSUE TITLE
Table header contains extra <th></th> at the end.

### ISSUE THREAD

**Issue by weinfurt** [IBM/carbon-components-angular#286] opened 2018-11-21 10:46 UTC
## Detailed description
Each table contains extra column at then end on top of what is defined in `model.header`. It is visible in the code of table.component.ts on [this line](https://github.com/IBM/carbon-components-angular/blob/9c71a969ab61887c7af6d842aee2a2b983e0a8db/src/table/table.component.ts#L274).

When a table is rendered in browser, the `scrollbarWidth` is calculated to a non-zero value (around 15px - depending on browser) in [window-tools.ts](https://github.com/IBM/carbon-components-angular/blob/master/src/utils/window-tools.ts).

Visual representation:
![table](https://user-images.githubusercontent.com/10806904/48835857-86077580-ed81-11e8-9ca5-0185297f0c23.png)

Notice, that table body does not have same width as header due to this issue. Also, the right border of the table body seems to be missing (or have different color). 

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Table component

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect that this extra header item is not present (or at least has 0 width) and table body has same width as table header with consistent borders around table.

> What browser are you working in?

Chrome, Firefox

> What version of the Carbon Design System are you using?

latest available

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

CA - IBM z/OSMF

## Steps to reproduce the issue

No steps needed. The issue is visible in [official storybook](https://angular.carbondesignsystem.com/?knob-size=md&knob-showSelectionColumn=true&knob-striped=true&knob-sortable=true&selectedKind=Table&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).

**Comment by esuau** [comment] 2018-12-06 09:15
This issue might have been resolved by #292 .

**Comment by acorbellini** [comment] 2019-02-20 16:57
I'm having the same issue. As @weinfurt mentioned, the extra header also made the rows lose their right border. The storybook has this issue in all examples, except for the skeleton one.

**Comment by cal-smith** [comment] 2019-02-21 20:35
dupe of #297 it's in our Q1 project, so we'll take a closer look soon

**Closed** 2019-02-21 20:35 UTC
Labels: component: Table

**Comment by stanislavgeorgiev** [comment] 2019-02-21 20:45
technically #297 is a dupe of this issue :-)
