### ISSUE TITLE
Dropdown - ERROR TypeError: this.wrapper.nativeElement.querySelector(...) is null

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#1482] opened 2020-08-31 03:13 UTC
## Detailed description

> Describe in detail the issue you're having.
I imported DropdownModule in my project and use \<ibm-dropdown-list\> tag, however, it always display Uncaught TypeError: boxMenu is null and dropdown list cannot show all items I identified.

> Is this a feature request (new component, new icon), a bug, or a general issue?
a bug.

> Is this issue related to a specific component?
ibm-dorpdown-list

> What did you expect to happen? What happened instead? What would you like to see changed?
Work normally. could list my dropdown list items.

> What browser are you working in?
FireFox.

> What version of the Carbon Design System are you using?
"carbon-components": "^10.6.1",
"carbon-components-angular": "^3.52.0",
"carbon-icons": "^7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
z/OSMF. Our schedule to finish the develop work by the end of September.

## Steps to reproduce the issue
1. add ibm-dropdown and ibm-dropdown-list in Html.
 \<div class="dropdown-wrapper"\>
        \<ibm-label\>Column
          \<ibm-dropdown #columnNameDropDowm
            [theme]="theme"
            [placeholder]="columnNameVl"
            [disabled]="disabled"
            [(ngModel)]="columnNameModel"
            [itemValueKey]="columnNameVl"
          \>
          \<ibm-dropdown-list [items]="clnItems"\>\</ibm-dropdown-list\>
          \</ibm-dropdown\>
        \</ibm-label\>
      \</div\>
2. add settings in ts file.
  @Input() columnNameVl = "INFO"; 
  @Input() filtCndtionVl = "INFO"; 
  @Input() columnValueVl = "columnValue"; 
  
  @Input() theme = "dark"; 
  @Input() disabled = false; 
  @Input() invalid = false;

  @ViewChild('columnNameDropDowm', {static: true}) columnNameDropDowm: Dropdown;
 @Input() columnNameModel = null; 
  @Input() clnItems = [
    { content: 'INFO' },
    { content: 'FINE' },
    { content: 'FINER' },
    { content: 'FINEST' },
    { content: 'SEVERE' },
    { content: 'WARNING' },
    { content: 'ALL' },
    { content: 'CONFIG' },
    { content: 'OFF' },
3. error happens.
ERROR TypeError: this.wrapper.nativeElement.querySelector(...) is null

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by MiraYuan** [comment] 2020-08-31 06:41
Even though it will not block ui, however, the error always display in console. So I reopen this issue.

**Comment by cal-smith** [comment] 2020-09-11 19:03
I can't reproduce this ... Make sure you're on the latest version

**Comment by zvonimirfras** [comment] 2021-01-14 15:14
Since we can't reproduce it and it looks like it might've been fixed in one of the later version, we'll close this.
If this is somehow still an issue, minimal reproduction environment that we can poke would be useful.

**Closed by zvonimirfras** 2021-01-14 15:14 UTC
