### ISSUE TITLE
IE Edge & Firefox ESR: Table with toolbar cannot hide one of toolbar-actions and toolbar-content

### ISSUE THREAD

**Issue by MiraYuan** [IBM/carbon-components-angular#892] opened 2019-11-06 09:40 UTC
## Detailed description

I'm not sure whether it is a bug or not because when I open carbon story in IE Edge, it could work well. However, in my project, it seems there is something wrong with the class whose name is "bx-batch-actions", the "clip-path" and "will-change-path" attributes in this class show error. 
This problem only existed in IE edge.

> What did you expect to happen? What happened instead? What would you like to see changed?
I expect it show as other browsers that tool bar actions not show content in UI when user not select any items of table.

> What browser are you working in?
Problem only existed in IE Edge.

> What version of the Carbon Design System are you using?
     "@carbon/icons-angular": "^10.4.0",
    "carbon-components": "^10.6.1",
    "carbon-components-angular": "^3.15.4",
    "carbon-icons": "^7.0.7",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
zOSMF 
## Steps to reproduce the issue
<ibm-table-container>
                <ibm-table-header>
                    <h4 ibmTableHeaderTitle>
                        {{ _messageService.getBundle('TABLE_TITLE_LOG_LEVEL') | translate}} 
                    </h4>
                    <p ibmTableHeaderDescription>{{ _messageService.getBundle('TABLE_DESC_LOG_LEVEL') | translate}}</p>
			          
                </ibm-table-header>
              <ibm-table-toolbar [model]="model">

                <ibm-table-toolbar-actions>
                  <button ibmButton="primary" (click)=delete()>
                      {{ _messageService.getBundle('BTN_DELETE') | translate}}
                      <ibm-icon-delete16 class="bx--btn__icon"></ibm-icon-delete16>
                  </button>
                  <button ibmButton="primary" 
                      id="setLogLevel"
                      (click)=setLogLevel()>
                      {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                      <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                  </button>
                </ibm-table-toolbar-actions> 

                <ibm-table-toolbar-content>

                    <button 
                    ibmButton="primary" size="sm" style="width: 90px"
                    id="save" (click)=save() >
                        {{ _messageService.getBundle('BTN_SAVE') | translate}}
                        <ibm-icon-save16 class="bx--btn__icon"></ibm-icon-save16>
                    </button>&nbsp;
                    
                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="resetDefault" (click)=resetDefault()> {{ _messageService.getBundle('BTN_RESTORE_DEFAULTS') | translate}}
                    </button>&nbsp;

                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="setAllLogLevel" (click)=setAllLogLevel()>
                    {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                        <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                    </button>&nbsp;
                    
                    <button ibmButton="primary" size="sm" style="width: 100px" (click)="openModal()">
                      {{ _messageService.getBundle('BTN_ADD_SERVICE') | translate}}
                        <ibm-icon-add20 class="bx--btn__icon"></ibm-icon-add20>
                    </button>
                    
                </ibm-table-toolbar-content>
              </ibm-table-toolbar>
           
              <ibm-table #tableContent
                style="display: block; width: 100%; min-height: 80px"
                [model]="model"
                [size]="size"
                [showSelectionColumn]="showSelectionColumn"
                [striped]="striped"
                [isDataGrid]="isDataGrid"
              >
              </ibm-table>
              <div *ngIf="showNoTableDataNotice" style="text-align:center;width:100%;">{{ _messageService.getBundle('TABLE_NO_DATA') | translate}}</div>
             
            </ibm-table-container>
...

  @Input() modalText = 'Hello, World'; //model for diaglogue
  @Input() model = new TableModel();
  @Input() size = 'md';
  @Input() showSelectionColumn = true;
  @Input() striped = false;
  @Input() isDataGrid = true;
  @Input() showNoTableDataNotice = true;
...

<ibm-table-container>
                <ibm-table-header>
                    <h4 ibmTableHeaderTitle>
                        {{ _messageService.getBundle('TABLE_TITLE_LOG_LEVEL') | translate}} 
                    </h4>
                    <p ibmTableHeaderDescription>{{ _messageService.getBundle('TABLE_DESC_LOG_LEVEL') | translate}}</p>
			          
                </ibm-table-header>
              <ibm-table-toolbar [model]="model">

                <ibm-table-toolbar-actions>
                  <button ibmButton="primary" (click)=delete()>
                      {{ _messageService.getBundle('BTN_DELETE') | translate}}
                      <ibm-icon-delete16 class="bx--btn__icon"></ibm-icon-delete16>
                  </button>
                  <button ibmButton="primary" 
                      id="setLogLevel"
                      (click)=setLogLevel()>
                      {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                      <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                  </button>
                </ibm-table-toolbar-actions> 

                <ibm-table-toolbar-content>

                    <button 
                    ibmButton="primary" size="sm" style="width: 90px"
                    id="save" (click)=save() >
                        {{ _messageService.getBundle('BTN_SAVE') | translate}}
                        <ibm-icon-save16 class="bx--btn__icon"></ibm-icon-save16>
                    </button>&nbsp;
                    
                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="resetDefault" (click)=resetDefault()> {{ _messageService.getBundle('BTN_RESTORE_DEFAULTS') | translate}}
                    </button>&nbsp;

                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="setAllLogLevel" (click)=setAllLogLevel()>
                    {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                        <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                    </button>&nbsp;
                    
                    <button ibmButton="primary" size="sm" style="width: 100px" (click)="openModal()">
                      {{ _messageService.getBundle('BTN_ADD_SERVICE') | translate}}
                        <ibm-icon-add20 class="bx--btn__icon"></ibm-icon-add20>
                    </button>
                    
                </ibm-table-toolbar-content>
              </ibm-table-toolbar>
           
              <ibm-table #tableContent
                style="display: block; width: 100%; min-height: 80px"
                [model]="model"
                [size]="size"
                [showSelectionColumn]="showSelectionColumn"
                [striped]="striped"
                [isDataGrid]="isDataGrid"
              >
              </ibm-table>
              <div *ngIf="showNoTableDataNotice" style="text-align:center;width:100%;">{{ _messageService.getBundle('TABLE_NO_DATA') | translate}}</div>
             
            </ibm-table-container>
...

  @Input() modalText = 'Hello, World'; //model for diaglogue
  @Input() model = new TableModel();
  @Input() size = 'md';
  @Input() showSelectionColumn = true;
  @Input() striped = false;
  @Input() isDataGrid = true;
  @Input() showNoTableDataNotice = true;
...

## Additional information
<ibm-table-container>
                <ibm-table-header>
                    <h4 ibmTableHeaderTitle>
                        {{ _messageService.getBundle('TABLE_TITLE_LOG_LEVEL') | translate}} 
                    </h4>
                    <p ibmTableHeaderDescription>{{ _messageService.getBundle('TABLE_DESC_LOG_LEVEL') | translate}}</p>
			          
                </ibm-table-header>
              <ibm-table-toolbar [model]="model">

                <ibm-table-toolbar-actions>
                  <button ibmButton="primary" (click)=delete()>
                      {{ _messageService.getBundle('BTN_DELETE') | translate}}
                      <ibm-icon-delete16 class="bx--btn__icon"></ibm-icon-delete16>
                  </button>
                  <button ibmButton="primary" 
                      id="setLogLevel"
                      (click)=setLogLevel()>
                      {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                      <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                  </button>
                </ibm-table-toolbar-actions> 

                <ibm-table-toolbar-content>

                    <button 
                    ibmButton="primary" size="sm" style="width: 90px"
                    id="save" (click)=save() >
                        {{ _messageService.getBundle('BTN_SAVE') | translate}}
                        <ibm-icon-save16 class="bx--btn__icon"></ibm-icon-save16>
                    </button>&nbsp;
                    
                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="resetDefault" (click)=resetDefault()> {{ _messageService.getBundle('BTN_RESTORE_DEFAULTS') | translate}}
                    </button>&nbsp;

                    <button 
                    ibmButton="primary" size="sm" style="width: 80px"
                    id="setAllLogLevel" (click)=setAllLogLevel()>
                    {{ _messageService.getBundle('BTN_SET_LOG_LEVEL') | translate}}
                        <ibm-icon-settings16 class="bx--btn__icon"></ibm-icon-settings16>
                    </button>&nbsp;
                    
                    <button ibmButton="primary" size="sm" style="width: 100px" (click)="openModal()">
                      {{ _messageService.getBundle('BTN_ADD_SERVICE') | translate}}
                        <ibm-icon-add20 class="bx--btn__icon"></ibm-icon-add20>
                    </button>
                    
                </ibm-table-toolbar-content>
              </ibm-table-toolbar>
           
              <ibm-table #tableContent
                style="display: block; width: 100%; min-height: 80px"
                [model]="model"
                [size]="size"
                [showSelectionColumn]="showSelectionColumn"
                [striped]="striped"
                [isDataGrid]="isDataGrid"
              >
              </ibm-table>
              <div *ngIf="showNoTableDataNotice" style="text-align:center;width:100%;">{{ _messageService.getBundle('TABLE_NO_DATA') | translate}}</div>
             
            </ibm-table-container>
...

  @Input() modalText = 'Hello, World'; //model for diaglogue
  @Input() model = new TableModel();
  @Input() size = 'md';
  @Input() showSelectionColumn = true;
  @Input() striped = false;
  @Input() isDataGrid = true;
  @Input() showNoTableDataNotice = true;
...

In IE Edge console:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/48002643/68286616-59e12380-00bc-11ea-952d-eff2fe51609e.png">

In Firefox console:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/48002643/68286679-75e4c500-00bc-11ea-80f3-b068c4659248.png">

**Comment by MiraYuan** [comment] 2019-11-06 11:28
<img width="676" alt="image" src="https://user-images.githubusercontent.com/48002643/68294590-83ee1200-00cb-11ea-8bb6-f5bb1e6b6063.png">
<img width="665" alt="image" src="https://user-images.githubusercontent.com/48002643/68294606-8a7c8980-00cb-11ea-8ac7-d5ea6bd48c32.png">

**Comment by cal-smith** [comment] 2019-11-06 16:02
Can you reproduce this issue on the carbondesignsystem.com site? It seems like the `clip-path` property isn't supported by Edge at the moment: https://caniuse.com/#feat=css-clip-path

This seems to be an issue with the `carbon-components` css, so I'd raise an issue on the `carbon` repo :+1:

**Comment by MiraYuan** [comment] 2019-11-08 02:30
Unfortunately, this problem was also existed in Firefox ESR, though it works well in Firefox 70.0.1.
In Firefox ESR, it has below two problems.
1. Same problem as IE Edge. In Firefox ESR console:
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/48002643/68444600-4a73ee80-0212-11ea-84a0-aea767eb56f5.png">
2. <textarea> show the height too much. 
In Firefox ESR UI
<img width="714" alt="image" src="https://user-images.githubusercontent.com/48002643/68444682-8909a900-0212-11ea-8509-2dc97b35e412.png">
In Firefox 70.0.1 UI
<img width="548" alt="image" src="https://user-images.githubusercontent.com/48002643/68444749-b8b8b100-0212-11ea-83c2-52f58dac7783.png">

**Comment by MiraYuan** [comment] 2019-11-08 02:31
<textarea
            ibmTextArea
            [invalid]="invalid"
            [pattern]="pattern"
            [(ngModel)]="packageCurrentInputValue"
            [value]="packageCurrentInputValue"
            placeholder="e.g. com.ibm.zoszmf.abc:com.ibm.zoszmf.xyz.*"
            rows=1
            cols=100
            required
            (change)="onChange($event)"
            aria-label="textarea"></textarea>

**Comment by cal-smith** [comment] 2019-11-08 15:34
Can you raise this issue in the [Carbon repo](https://github.com/carbon-design-system/carbon/issues/new/choose) - it appears to be styling related, so there's nothing we can do on our end.

**Comment by zvonimirfras** [comment] 2021-01-18 20:46
This appears to be resolved in the carbon repo so the changes should trickle down. Feel free to reopen if needed.

**Closed by zvonimirfras** 2021-01-18 20:46 UTC
Labels: bug, style
