### ISSUE TITLE
The content of tabs are not loaded properly if traversing is not done with a sequential way.

### ISSUE THREAD

**Issue by chandbh9** [IBM/carbon-components-angular#708] opened 2019-08-19 15:59 UTC
I am facing issue with carbon tab view in angular. Once I clicked on 1st tab and going sequentially then all component for each tab loaded properly but once I clicked on 3rd or 4th directly the content is not loaded and then if I clicked in any other part of that blank page then its loaded.

<div>
    <ibm-tabs [followFocus]="followFocus" [isNavigation]="isNavigation">
      <ibm-tab heading="Employee Details">
        <app-emp-details #emp [requestResumeName]="requestResumeName" [resumeOfUrl]="resumeOfUrl" [canEdit]="canEdit" [loadedData]="loadedData" [empForm]="empForm" [empSubmit]="empSubmit" [resumeFlag]="resumeFlag"></app-emp-details>
      </ibm-tab>
      <ibm-tab heading="Client Information">
        <app-client-information [canEdit]="canEdit" [loadedData]="loadedData" [clientForm]="clientForm" [clientSubmit]="clientSubmit"></app-client-information>
      </ibm-tab>
       <ibm-tab heading="Assignment Details">
        <app-assignment-details [canEdit]="canEdit" [loadedData]="loadedData" [assignmentForm]="assignmentForm" [endDateinvalid]="endDateinvalid" [invalid]="invalid" [startDateinvalid]="startDateinvalid"  [assignmentSubmit]="assignmentSubmit"></app-assignment-details>
      </ibm-tab>
     
      <ibm-tab heading="Request Details">
          <app-request-detail [canEdit]="canEdit" [checkboxInvalid]="checkboxInvalid" [loadedData]="loadedData" [business_justification]="business_justification"  [requestForm]="requestForm"  [requestSubmit]="requestSubmit"></app-request-detail>
      </ibm-tab>
      <div *ngIf="exceptionTab">
     <ibm-tab heading="Exception Approval Request">
        <app-exception-request [canEdit]="canEdit" [loadedData]="loadedData" [exceptionForm]="exceptionForm" [exceptionSubmit]="exceptionSubmit"></app-exception-request>
      </ibm-tab>
    </div>
    
      
    </ibm-tabs>
  </div>

not only that if I want show/hide the last tab then also facing this issue until I am clicking on the window to load the component, in the above code I have commented those lines.

**Comment by zvonimirfras** [comment] 2019-09-10 20:50
If you try removing the `div` with the `ngIf` and replace the content of tabs with simple text, do you still experience the problem?

Could you create a minimal reproduction in stackblitz or similar ([this](https://stackblitz.com/edit/carbon-angular-base) might be a good start) if yes?

**Comment by zvonimirfras** [comment] 2021-01-18 21:34
It's been a long time since the last update and we can't reproduce, so closing, feel free to reopen with reproduction steps.

**Closed by zvonimirfras** 2021-01-18 21:34 UTC
Labels: bug, component: Tabs
