### ISSUE TITLE
Additional th is messing up table component style

### ISSUE THREAD

**Issue by scarraway** [IBM/carbon-components-angular#146] opened 2018-10-02 14:45 UTC
Additional th is messing up table component style

## Detailed description
It seems that the custom templates are messing up the number of table headers, and it's causing some display weirdness.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Table component

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect the number of table headers to match the number of data columns, and the last table header to have a proper right border.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v 1.8.1

## Steps to reproduce the issue
Create a table with a custom template. This is shown in the table storybook.

![image](https://user-images.githubusercontent.com/8643648/46355662-42b94200-c62f-11e8-9594-f700293c4ecb.png)

**Comment by zvonimirfras** [comment] 2018-10-02 15:54
Duplicate of #54 

Correct approach to this is to update styles, here's the open issue for that in carbon-components: https://github.com/IBM/carbon-components/issues/1124

**Closed by zvonimirfras** 2018-10-02 15:54 UTC
Labels: duplicate

**Comment by scarraway** [comment] 2018-10-02 16:40
Thanks @zvonimirfras Didn't see the existing issue
