### ISSUE TITLE
File upload component - It will let you upload multiple files even "multiple is false" in case of drag and drop.

### ISSUE THREAD

**Issue by amirkhan064** [IBM/carbon-components-angular#1049] opened 2020-02-07 05:32 UTC
when multiple is false and you are trying to upload a file by clicking on the upload link its working fine, replacing the old file with the new one.
But if you drag a file to upload it will let you upload the multiple files.

i am using -
"carbon-components": "^10.9.3",
"carbon-components-angular": "^3.38.0",

**Comment by HYACCCINT** [comment] 2020-02-07 14:16
Duplicate of #1045 ?

**Comment by cal-smith** [comment] 2020-02-07 15:28
Looks like it ... closing in favor of #1045

**Closed by cal-smith** 2020-02-07 15:28 UTC
