### ISSUE TITLE
<ibm-toast>   showClose has to be true by default 

### ISSUE THREAD

**Issue by tulasigudibanda** [IBM/carbon-components-angular#1039] opened 2020-02-04 21:04 UTC
The carbon toast component should have showClose set to true to render the close icon by default.
<ibm-toast *ngIf="showToastNotification" (close)="closeToastNotification()" [notificationObj]="notificationObj">
 </ibm-toast>

Right now , we need to set it as part of notificationObj to make it work:
this.notificationObj = {
        type: 'warning',
        title: '',
        subtitle: '',
        caption: ``,
        lowContrast: false,
        showClose: true
      }

**Comment by HYACCCINT** [comment] 2020-02-05 18:49
@tulasigudibanda Hello, we were not able to reproduce this issue, would it be possible for you to send a showcase of code that is causing the bug?

**Comment by ninja511** [comment] 2020-06-29 16:59
closing pending additional information: can't reproduce

**Closed by ninja511** 2020-06-29 16:59 UTC
Labels: bug, can't reproduce, component: Notification
