### ISSUE TITLE
Table with expansion: incorrect row heights

### ISSUE THREAD

**Issue by dianatran18** [IBM/carbon-components-angular#1104] opened 2020-03-04 16:09 UTC
For the smaller table sizes, the row heights are not changing for the "small" and "short table size (both in the collapsed row and expanded row). 
The alignment is off for the chevrons, checkboxes, and text as well. 

Current:

Small
<img width="627" alt="Screen Shot 2020-03-04 at 11 06 40 AM" src="https://user-images.githubusercontent.com/43549567/75898564-3c249080-5e08-11ea-8f39-ebb612d7e881.png">

Short
<img width="631" alt="Screen Shot 2020-03-04 at 11 07 10 AM" src="https://user-images.githubusercontent.com/43549567/75898620-4e9eca00-5e08-11ea-97e6-8d48a968eea2.png">

Normal
<img width="626" alt="Screen Shot 2020-03-04 at 11 10 08 AM" src="https://user-images.githubusercontent.com/43549567/75898881-b7864200-5e08-11ea-8c30-837b4e5db347.png">

Large
<img width="631" alt="Screen Shot 2020-03-04 at 11 08 18 AM" src="https://user-images.githubusercontent.com/43549567/75898723-768e2d80-5e08-11ea-8e19-115bc84ad1fe.png">

—————

Expected heights: 
<img width="896" alt="Screen Shot 2020-03-04 at 11 05 52 AM" src="https://user-images.githubusercontent.com/43549567/75898489-1e572b80-5e08-11ea-88e9-92622bc9efe8.png">

**Comment by cal-smith** [comment] 2020-03-04 16:31
duplicate of #1094

**Closed by cal-smith** 2020-03-04 16:31 UTC
Labels: bug, component: Table, style
