### ISSUE TITLE
Bidi support for Accordion component: some of the UI layouts are not mirrored.

### ISSUE THREAD

**Issue by DavidSCChen** [IBM/carbon-components-angular#1614] opened 2020-11-17 06:36 UTC
## Detailed description

> Describe in detail the issue you're having.

Bidi support for Accordion component: some of the UI layouts are not mirrored.
Found that only the arrow (open&collapse) icon is mirrored under "Right to Left" orientation, but the title in the accordion-item is not mirrored.  Also the content in the accordion-item should attach to the right, not in the middle.   Issues are highlight in the screenshots.

> Is this a feature request (new component, new icon), a bug, or a general issue?

General issue

> Is this issue related to a specific component?

Bidi support

> What did you expect to happen? What happened instead? What would you like to see changed?

When the Accordion component under the "Right to Left" orientation, the whole UI layout should be mirrored. but currently only the arrow icon is mirrored.

> What browser are you working in?

Chrome & Firefox

> What version of the Carbon Design System are you using?

"carbon-components": "^10.21.0"
"carbon-components-angular": "^4.19.1"

## Steps to reproduce the issue
Place the Accordion component inside a div, and add the attribute dir="rtl" to the div.

## Additional information

* Screenshots:
Left to Right:
![圖片](https://user-images.githubusercontent.com/54974983/99352427-9786a800-28dd-11eb-863b-c998ed38e2d1.png)

Right to Left:
![圖片](https://user-images.githubusercontent.com/54974983/99354106-bb97b880-28e0-11eb-9ab5-640942fd8b77.png)

**Comment by cal-smith** [comment] 2020-11-17 18:55
This may be a style issue - we shouldn't be doing anything that would explicitly prevent bidirectional text from working. Can you reproduce this in the react storybook (https://react.carbondesignsystem.com)?

**Comment by DavidSCChen** [comment] 2020-11-18 02:42
@cal-smith 
I had reproduced this issue in the sandbox:
https://codesandbox.io/s/carbon-components-react-accordion-bidi-issues-5tblb?file=/src/index.js

**Comment by cal-smith** [comment] 2020-11-18 18:31
Great! So it looks like this is an issue upstream with the Carbon styles ... This will need to be opened as an issue over in https://github.com/carbon-design-system/carbon

**Comment by asudoh** [comment] 2020-11-19 02:09
As noted in https://github.com/carbon-design-system/carbon/blob/v10.23.0/packages/components/docs/g11n.md, Carbon style has to go through RTLCSS toolchain to get RTL version of the style. @DavidSCChen Would you try doing that in your CodeSandbox example?

**Comment by DavidSCChen** [comment] 2020-12-15 06:22
@cal-smith @asudoh 
I had managed to apply the RTLCSS in the sandbox, and proved the bidi layout issue could be resolved by RTLCSS, so this should be a non-issue.
https://codesandbox.io/s/webpack-react-rtlcss-carbon-accordion-xktfk

**Comment by cal-smith** [comment] 2021-01-06 20:09
Sweet, I'll close this then since it's been resolved

**Closed by cal-smith** 2021-01-06 20:09 UTC
Labels: component: Accordion, i18n, style
