### ISSUE TITLE
Menu items in <ibm-header> disappear too soon when window is resized

### ISSUE THREAD

**Issue by daveweaverweather** [IBM/carbon-components-angular#1140] opened 2020-03-20 11:14 UTC
Using a simple header for my app:

```
<ibm-header>
	<ibm-header-navigation>
		<ibm-header-item>Hello</ibm-header-item>
		<ibm-header-item>World</ibm-header-item>
	</ibm-header-navigation>
</ibm-header>
```

When the window width is reduced, these menu items disappear when there is still plenty of room available for them to be displayed.

I would expect the menus to remain visible until there wasn't enough space to display them.

![image](https://user-images.githubusercontent.com/27726764/77158358-0edc1180-6a9b-11ea-83bb-cd14b0ea06e9.png)

Happens in all tested browsers: Chrome, Firefox, IE11, Edge.

Using  carbon-components-angular 3.44.2

**Comment by zvonimirfras** [comment] 2021-01-18 15:28
Since this happens by design and there is a [simple workaround](https://github.com/carbon-design-system/carbon-tutorial-angular/blob/angular-step-3/src/assets/scss/carbon-overrides.scss#L24-L27), should we keep this open? @cal-smith 

If it changes in design it will be fixed automagically.

**Comment by cal-smith** [comment] 2021-01-18 15:51
Let me dig around a bit in Carbon ... This is definitely something that should be addressed with an optional class on the components level, and I wonder if that's available now.

**Comment by cal-smith** [comment] 2021-01-19 21:34
So it appears the solution here is to have the sidenav dynamically appear when the items disappear ... We probably need to go over the whole code and storybook examples to make sure we can (easily!) do something like this: https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation-actions-and-side-nav (resize to see the behavior)

**Comment by stanislavgeorgiev** [comment] 2021-06-24 18:19
Check the new example: https://angular.carbondesignsystem.com/?path=/story/components-ui-shell--header-fluid-items-to-side-navigation

@cal-smith I think this issue can be closed.

**Comment by cal-smith** [comment] 2021-06-24 18:20
Awesome, agreed!

**Closed by cal-smith** 2021-06-24 18:20 UTC
Labels: bug, component: UI Shell, enhancement, style
