### ISSUE TITLE
Code Snippet does not have "Show more" button in some cases

### ISSUE THREAD

**Issue by yelyzavetachebanova** [IBM/carbon-components-angular#1077] opened 2020-02-25 17:03 UTC
Code Snippet does not have "Show more" button in some cases

Code Snippet component has "Show more" button which is by default visible in the bottom right corner. Sometimes this button is not visible and appears only after a click inside the component area.

![Code-Snippet-without-Show-More](https://user-images.githubusercontent.com/39129628/75269024-91551680-57f8-11ea-88f7-0cf664d338fe.gif)

carbon-components version: 9.91.5

**Comment by cal-smith** [comment] 2020-02-25 20:38
This is with v2 correct? It would be awesome if you could figure out a fix and submit a PR to the v9 branch 👍 Otherwise we'll try to take a look

**Comment by yelyzavetachebanova** [comment] 2020-02-26 07:59
Yes, it is v2, to be precise carbon-components-angular: 2.49.10

**Comment by yelyzavetachebanova** [comment] 2020-02-26 09:37
Unfortunately I won't have time to work on fix for this problem

**Comment by cal-smith** [comment] 2020-02-26 21:20
> Unfortunately I won't have time to work on fix for this problem

Okay ... We're focused on prepping for v4 and Angular 9 support right now, but we should be able to take a look after

**Comment by yelyzavetachebanova** [comment] 2020-05-13 14:19
Hi, 
just checking the status of this issue.

Thanks!

**Comment by cal-smith** [comment] 2020-05-13 22:19
Hey! Sorry for the delay, there's been a lot going on with v4 and some of the icons updates ... v2 isn't in our support plan going forwards, but we'll still accept community fixes. Since this issue was opened before v4 we'll try to take a look at it, but if you could create a minimal reproduction environment (ng cli repo) and/or propose a solution that would be super helpful!

**Comment by zvonimirfras** [comment] 2021-01-18 16:13
Considering everything, we won't be fixing this but we will take in a community contribution if one comes, as Cal mentioned.
That said, we don't need to track it any more.

**Closed by zvonimirfras** 2021-01-18 16:13 UTC
Labels: bug, component: CodeSnippet, wontfix
