### ISSUE TITLE
Dropdown options in a modal not positioned correctly

### ISSUE THREAD

**Issue by sparikh1594** [IBM/carbon-components-angular#519] opened 2019-04-29 19:41 UTC
Dropdown menu options inside a modal dialog show up behind the modal dialog

## Detailed description

> Describe in detail the issue you're having.

![image](https://user-images.githubusercontent.com/43587264/56922013-16a65800-6a7c-11e9-9170-024909a42888.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

Dropdown , Modal

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by cal-smith** [comment] 2019-05-06 13:55
Looks like the root cause is here: https://github.com/carbon-design-system/carbon-components/issues/1064

@sparikh1594 feel free to :+1: that issue as well, ideally we'll want to have it fixed in `carbon-components` - in the short term you can target `.bx--list-box__menu` with `z-index: 9001;`

**Comment by cal-smith** [comment] 2019-05-13 14:36
PR in Carbon to fix the issue: https://github.com/carbon-design-system/carbon/pull/2660

**Comment by cal-smith** [comment] 2019-06-11 17:24
Should be fixed as of carbon `10.2`/`10.3`

**Closed by cal-smith** 2019-06-11 17:24 UTC
Labels: bug, component: Dropdown, style
