### ISSUE TITLE
Datepicker causes "object does not support property or method 'closest'" and results in infinite loop Error in IE

### ISSUE THREAD

**Issue by thesupernvk** [IBM/carbon-components-angular#977] opened 2019-12-23 10:57 UTC
## Detailed description

> Describe in detail the issue you're having.

Using ibm-date-picker component results in error "object does not support property or method 'closest'" and causes infinite loop. The browser becomes unusable due to this.

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug

> Is this issue related to a specific component?

ibm-date-picker

> What did you expect to happen? What happened instead? What would you like to see changed?

It should not throw errors. Polyfills/incompatibality with IE should be handled at component level if possible.

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

"carbon-components": "^10.6.2",
"carbon-components-angular": "^3.30.3"

## Additional information

* Screenshots or code

![image](https://user-images.githubusercontent.com/38689367/71353842-41f82d00-25a0-11ea-9963-08dab5ca3b5b.png)

* Notes

This issue happens on IE11. As discussed here: https://github.com/IBM/carbon-components-angular/issues/774#issuecomment-564071336, tried to install the polyfill but still facing the issue.

**Comment by cal-smith** [comment] 2019-12-23 16:15
You'll need to add a polyfill for `closest` ... We'll definitely add a section to the readme that covers this better

**Comment by thesupernvk** [comment] 2019-12-24 12:17
> You'll need to add a polyfill for `closest` ... We'll definitely add a section to the readme that covers this better

We already tried by adding polyfill for closest. (https://www.npmjs.com/package/element-closest)
It did not solve the issue of infinite loop on IE.

Currently all our pages having datepicker component are failing on IE.

**Comment by cal-smith** [comment] 2019-12-24 17:29
I'll open this back up for further investigation, but from what I recall we had the fix confirmed on our end by polyfilling closest ... if you can provide a minimal repro environment that would help debugging (just a minimal angular cli repo would be perfect)

**Comment by lennerd** [comment] 2020-03-20 07:57
There is another thing worth mentioning: The reason the IE is spawning this endless amount of errors is because the date picker component is triggering an endless amount of change detection checks. Any idea why this is happening?

**Comment by cal-smith** [comment] 2020-03-24 18:56
Not offhand ... The only thing I could think of would be a bad getter returning new objects

**Comment by lennerd** [comment] 2020-03-25 06:22
My bad. There was a bug in the version we used of `carbon-components-angular` (requestAnimationFrame not used outside the zone). Now everything is working again.

**Comment by cal-smith** [comment] 2020-03-25 16:13
Nice! Yeah that was an unfortunate bug ...

**Comment by zvonimirfras** [comment] 2021-03-11 16:10
> My bad. There was a bug in the version we used of `carbon-components-angular` (requestAnimationFrame not used outside the zone). After we made an update the bug was fixed.

So, already fixed in a newer version 🙌

**Closed by zvonimirfras** 2021-03-11 16:10 UTC
Labels: IE11, component: Date Picker
