### ISSUE TITLE
Accordion align="end" not behaving as expected

### ISSUE THREAD

**Issue by Donisius** [IBM/carbon-components-angular#2023] opened 2022-02-17 21:37 UTC
Accordion content should remain left aligned when `align` is set to `end`. Only the chevron in the accordion header should be right aligned.

* Screenshots or code

## What is expected:
![image](https://user-images.githubusercontent.com/45505172/154574791-9e414971-6d00-453b-b1ac-dcae41b2d77e.png)

## What is actually rendered:
![image](https://user-images.githubusercontent.com/45505172/154574836-ebe032b5-a3d8-438f-8308-f0981bbcd7e4.png)

**Comment by Akshat55** [comment] 2022-10-04 21:01
Closing issue, cannot duplicate in current version of CCA and could possibly be have been caused by carbon-components styles package. Updating all packages to latest Carbon v10 will fix.

Image from storybook
![image](https://user-images.githubusercontent.com/38994122/193927465-aa582a4b-946a-4593-89f3-e9be4b9af59d.png)

**Closed by Akshat55** 2022-10-04 21:01 UTC
